name: Storybook
on:
  push:
    branches:
      - 'main'
    paths: 
      - 'packages/storybook'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          yarn run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: 'packages/storybook/storybook-static' # output folder from `npm run build-storybook`