name: "Release Workflow"
on:
  # No auto run
  workflow_dispatch:

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          #token: ${{ secrets.OUR_SECRET_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install packages
        run: yarn
      - name: Build packages 
        run: yarn build
      - name: Run our tests
        run: yarn test
      - name: Bumb versions and publish with changesets
        run: |
          # Bump versions
          yarn changeset version
          # Publish to npm 
           yarn changeset publish
          # Need to change slightly, as there is a known issue with workspace:^ versioning
          # Issue: https://github.com/changesets/changesets/issues/432
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}